# Use 'smart-path' renderer for the source
file:
  renderers:
    - smart-path

# Use 'buffer' previewer for the source
line:
  previewers:
    - buffer

# Use 'buffer' previewer for the source
buffer:
  previewers:
    - buffer

helptag:
  defaultAction: cmd:helptag

  actions:
    - cmd:helptag

  renderers:
    - helptag

  previewers:
    - helptag

# Fallback setting
"":
  # Use 'open' as a default action (invoked by <Return>)
  defaultAction: open

  # Allow the following actions
  actions:
    - debug
    - open
    - open:split
    - open:vsplit
    - open:tabedit
    - quickfix

  # Use 'to-relative-path' projector to prefer relative path
  # Use 'fzf-matcher' projector to filter/sort items
  projectors:
    - to-relative-path
    - fzf-matcher

  # Try several previewers to preview the content of the item
  previewers:
    - file
    - buffer
    - attribute

  # Use 'fzf' projector to filter/sort actions
  actionProjectors:
    - fzf-matcher

  # Use 'attribute:description' previewer to preview actions
  actionPreviewers:
    - attribute:description

# JSON schema of this file
# yaml-language-server: $schema=https://raw.githubusercontent.com/lambdalisue/vim-fall/main/denops/fall/config/picker/schema.json
$schema: https://raw.githubusercontent.com/lambdalisue/vim-fall/main/denops/fall/config/picker/schema.json
