type: object
required:
  - $schema
additionalProperties: false
properties:
  $schema:
    type: string
patternProperties:
  "^[a-zA-Z0-9_\\-:]*$":
    type: object
    description: |
      Picker options of the source.
    additionalProperties: false
    properties:
      actionAliases:
        description: |
          The list of action aliases.
        type: object
        additionalProperties: false
        patternProperties:
          "^[a-zA-Z0-9_\\-:]*$":
            type: string
      defaultAction:
        description: |
          The default action to perform.
        type: string
      actions:
        description: |
          The list of actions available to invoke.
        type: array
        items:
          type: string
      projectors:
        description: |
          The list of projectors available in the source picker.
        type: array
        items:
          type: string
      renderers:
        description: |
          The list of renderers available in the source picker.
        type: array
        items:
          type: string
      previewers:
        description: |
          The list of previewers available in the source picker.
        type: array
        items:
          type: string
      actionProjectors:
        description: |
          The list of projectors available in the action picker.
        type: array
        items:
          type: string
      actionRenderers:
        description: |
          The list of renderers available in the action picker.
        type: array
        items:
          type: string
      actionPreviewers:
        description: |
          The list of previewers available in the action picker.
        type: array
        items:
          type: string
      options:
        description: |
          Picker options.
        type: object
        additionalProperties: false
        properties:
          redraw:
            type: object
            additionalProperties: false
            properties:
              interval:
                description: |
                  Interval in millisecond to redraw screen.
                type: number
          preview:
            type: object
            additionalProperties: false
            properties:
              mode:
                description: |
                  Preview highlight mode.
                type: string
                enum:
                  - "fast"
                  - "correct"
          itemCollector:
            type: object
            additionalProperties: false
            properties:
              threshold:
                description: |
                  The maximum number of the items to collect.
                type: number

# JSON schema of this file
# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
$schema: "http://json-schema.org/draft-07/schema"
