source:
  # Exclude some files from the result
  file:
    options:
      excludes:
        - ".*/\\.DS_Store"
        - ".*/\\.git/.*"
        - ".*/\\.cache/.*"
        - ".*/\\.Trash/.*"
        - ".*/node_modules/.*"
        - ".*/target/.*"

  rg:
    options:
      excludes:
        - ".*/\\.DS_Store"
        - ".*/\\.git/.*"
        - ".*/\\.cache/.*"
        - ".*/\\.Trash/.*"
        - ".*/node_modules/.*"
        - ".*/target/.*"

action:
  # Open quickfix window after `quickfix` action
  quickfix:
    options:
      after: copen

# JSON schema of this file
# yaml-language-server: $schema=https://raw.githubusercontent.com/lambdalisue/vim-fall/main/denops/fall/config/extension/schema.json
$schema: https://raw.githubusercontent.com/lambdalisue/vim-fall/main/denops/fall/config/extension/schema.json
