type: object
required:
  - $schema
additionalProperties: false
properties:
  $schema:
    type: string
patternProperties:
  "^(source|transformer|projector|renderer|previewer|action)$":
    description: |
      Extension options map for the kind.
      The key is the name (with variant) of extension and the value is options of extension.
    type: object
    additionalProperties: false
    patternProperties:
      "^[a-zA-Z0-9_\\-:]*$":
        type: object
        description: |
          Extension options.
          See the extension's documentation for valid options.

# JSON schema of this file
# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
$schema: "http://json-schema.org/draft-07/schema"
